name: gmso
channels:
  - conda-forge
dependencies:
  - python >=3.8, <3.12
  - boltons
  - numpy
  - sympy
  - unyt>=2.9.5
  - boltons
  - lxml
  - pydantic>=2
  - networkx
  - ele>=0.2.0
  - foyer>=0.11.3
  - forcefield-utilities>=0.2.1
  - symengine
  - python-symengine
  - importlib_resources
