name: flowermd-dev
channels:
  - conda-forge
dependencies:
  - foyer >=0.12.0
  - fresnel
  - freud >=2.13.1
  - gmso >=0.11.2
  - gsd >=3.0
  - grits=0.4.1
  - hoomd=4.3
  - mbuild >=0.17.0
  - numpy
  - openbabel >=3
  - pip
  - pre-commit
  - py3Dmol
  - pytest
  - pytest-cov
  - nbmake
  - python >=3.10, <3.12
  - fresnel >=0.13.5
  - cmeutils >=1.1.1
